### ISSUE TITLE
Merge into Crystal stdlib

### ISSUE THREAD

**Issue by ysbaddaden** [ysbaddaden/execution_context#11]
Tracks the progression to get ExecutionContext merged into Crystal's stdlib.

**Features**

- [x] https://github.com/crystal-lang/crystal/pull/14532
- [x] https://github.com/crystal-lang/crystal/pull/14568
  - [x] Support libevent2
  - [x] Support Win32/IOCP
- [x] Bring back thread-safety to `Fiber::StackPool`
- [x] `Thread::WaitGroup` (maybe not needed)
- [ ] `Fiber#status`
- [x] `Thread.each` (+ consider safe `Fiber.each`)

**Patches / Refactors**

- [x] https://github.com/crystal-lang/crystal/pull/14543
- [x] https://github.com/crystal-lang/crystal/pull/14554
- [x] https://github.com/crystal-lang/crystal/pull/14555
  - [x] https://github.com/crystal-lang/crystal/pull/14561
  - [x] https://github.com/crystal-lang/crystal/pull/14560
  - [x] https://github.com/crystal-lang/crystal/pull/14559
- [ ] ~~https://github.com/crystal-lang/crystal/pull/14558~~
- [x] `Crystal.main` explicitly calls to `LibC._exit`

**Comment by ysbaddaden** [comment]
Done.
